### ISSUE TITLE
Convert OST file to PST file?

### ISSUE THREAD

**Issue by kiquenet** [asposeemail/Aspose_Email_NET#26]
HOW-TO Convert OST file to PST file, without Outlook installed ?

https://github.com/aspose-email/Aspose.Email-for-.NET/blob/b1dfbe3e84376965aa59415fd06ce77e8d45cf9b/Examples/CSharp/Outlook/ConvertOSTToPST.cs

How Aspose.Email-for-.NET costs for a single home developer? Not free.

**Comment by kashifiqb** [comment]
You can convert OST to PST using Aspose.Email API without installing MS Outlook. The following code can be used for this purpose.

using (PersonalStorage personalStorage = PersonalStorage.FromFile("test.ost"))
{
    personalStorage.SaveAs("test.pst", FileFormat.Pst);
}

However, please note that at present, the API supports converting OST formats to PST except OST 2013/2016.

For cost inquiries, please post your query in [Aspose.Purchase forum](https://www.aspose.com/community/forums/aspose.purchase/220/showforum.aspx) to get further assistance.

**Comment by avinag** [comment]
If you want to get exchange OST data which is corrupted due to several reasons, so don't worry you can try eSoftTools [OST to PST](http://www.esofttools.com/ost-recovery/) Converter software for best result and simply to convert OST to PST file along with emails, contacts, calendar, notes, attachment, etc. Software has benefits to convert single and multiple folders. Try free demo OST to PST converter software which has ability to convert OST file freely and after satisfied you can buy complete featured software. 

get more info:- http://www.esofttools.com/export-ost-to-pst.html

**Comment by ronnie-miller** [comment]
You can use OST to PST Converter, This Software capable to Convert multiple OST files into PST format without any disturbance.  For more information: https://www.freeviewer.net/forum/how-to-extract-emails-from-outlook-ost-file

**Comment by mayurbadgujar** [comment]
I am getting an error "The process cannot access the file 'MyOSTFilePath' because it is being used by another process"

using (PersonalStorage personalStorage = PersonalStorage.FromFile("test.ost"))
{
personalStorage.SaveAs("test.pst", FileFormat.Pst);
}

with this code

**Comment by mudassirfayyaz** [comment]
@mayurbadgujar ,

From error message it seems that the source OST file is being opened by some other program like MS Outlook or some thing else. Before loading using Aspose.Email, please make sure it is not being opened any where else. Please also check following documentation link for your kind reference.

https://docs.aspose.com/display/emailnet/Read+and+Convert+Outlook+OST+File#ReadandConvertOutlookOSTFile-ReadingOSTFiles

**Comment by PauloTroguilho** [comment]
hi, help me... method no implemented in convert ost to psd....

**Comment by shahzad-latif** [comment]
@PauloTroguilho 

Kindly post your issue along with the sample code and input files etc. in our [free support forums](https://forum.aspose.com/), so our team can properly help, track, and follow up the issue. Thanks.

**Comment by lurious23** [comment]
I have a solution to convert OST files to PST files with the help of ToolsBaer OST to PST Conversion Tool through this tool users can convert any number of OST files into PST without any technical issues. This is the best solution if you want to only view your OST file and if you want to convert an OST file then through this tool you can convert the OST file into PST smoothly without any restrictions. This application provides a free preview so that you can see your entire offline .ost file data without any restriction. Install this tool on any version of Windows and Mac operating systems and operate a free trial. This is a wonderful tool you should try if you don't want any error while converting your ost file.
